# Generated by Django 6.0.1 on 2026-02-02 16:53

import PlayHub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('plataforma', models.CharField(choices=[('PC', 'PC'), ('PS', 'PlayStation'), ('XB', 'Xbox'), ('SW', 'Switch')], max_length=2)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4, validators=[PlayHub.models.validar_precio])),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
