# Generated by Django 6.0.1 on 2026-02-02 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayHub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juego_titulo', models.CharField(max_length=100)),
                ('usuario_username', models.CharField(max_length=30)),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comentario', models.TextField(validators=[django.core.validators.MinLengthValidator(50)])),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='juego',
            old_name='fecha',
            new_name='fecha_lanzamiento',
        ),
    ]
