# Generated by Django 6.0.2 on 2026-02-05 21:51

import PlayHub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayHub', '0002_reseña_rename_fecha_juego_fecha_lanzamiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reseña',
        ),
        migrations.AlterField(
            model_name='juego',
            name='fecha_lanzamiento',
            field=models.DateField(verbose_name='Fecha de la lanzamiento'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='plataforma',
            field=models.CharField(choices=[('PC', 'PC'), ('PS', 'PlayStation'), ('XB', 'Xbox'), ('SW', 'Switch')], max_length=2, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[PlayHub.models.validar_precio], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
    ]
